In [1]:
import numpy as np

list1 = ['a','b','c']
list2 = [10,20,30]

for i,j in zip(list1,list2):
    print(i,' ',j)

a   10
b   20
c   30


In [1]:
lines = {}
lines['Ha'] = [0,10,2]
lines['Hb'] = [0,11,3]

print(lines)

{'Ha': [0, 10, 2], 'Hb': [0, 11, 3]}


In [7]:
for l in lines:
    print (lines[l])

[0, 10, 2]
[0, 11, 3]


In [21]:
import numpy as np

m = np.array([1,1,1,0,0,0,1,1,1,0,0,0,1,1,1,1,1,0,0,0,0], dtype=bool)
m = m.astype(int)
dm = m[1:]-m[:-1]

if m[0] == 0:
    start = [0]
else:
    start = []
s, = np.where(dm==-1)
start.extend(list(s))
print(start)
end, = np.where(dm == 1)
end = list(end)
if m[-1] == 0:
    end.append(len(m)-1)
print(end)

[2, 8, 16]
[5, 11, 20]


In [17]:
masked = [(i,j) for (i,j) in zip(start,end)]

In [18]:
print(masked)

[(2, 5), (8, 11), (16, 20)]


## FITS table

In [43]:
from astropy.io import fits

path = '/Users/dfadda/Python/VIMOS/MOSA85V11/QUAD1/'
file = 'MOSA85V11_OBJECT_SCI_TABLE.fits'

hdul = fits.open(path+file)
header = hdul[0].header
data = hdul[1].data 
cols = hdul[1].columns
#hdul.info()
#cols.info()
hdul.close()

header

SIMPLE  =                    T / file does conform to FITS standard             
BITPIX  =                   16 / number of bits per data pixel                  
NAXIS   =                    0 / number of data axes                            
EXTEND  =                    T / FITS dataset may contain extensions            
COMMENT   FITS (Flexible Image Transport System) format is defined in 'Astronomy
COMMENT   and Astrophysics', volume 376, page 359; bibcode: 2001A&A...376..359H 
DATE    = '2015-02-06T13:07:01' / file creation date (YYYY-MM-DDThh:mm:ss UT)   
ORIGIN  = 'ESO     '           / European Southern Observatory                  
MJD-OBS =       56545.24003974 / Obs start 2013-09-10T05:45:39.433              
DATE-OBS= '2013-09-10T05:45:39.433' / Date of observation                       
TELESCOP= 'ESO-VLT-U3'         / ESO <TEL>                                      
RA      =            10.401636 / 00:41:36.3 RA (J2000) pointing                 
DEC     =             -9.683

In [42]:
from astropy.io import fits
path = '/Users/dfadda/Python/VIMOS/MOSA85V11/QUAD1/'
file = 'MOSA85V11_OBJECT_SCI_TABLE.fits'

from astropy.table import Table
dat = Table.read(path+file, format='fits')
df = dat.to_pandas()

df

slit_id         xtop         ytop      xbottom      ybottom     xwidth  \
0       8.0     0.924530  2807.975456   148.043810  2809.111440  17.655001   
1       9.0   212.992077  1679.912498   314.742539  1680.555636  12.161000   
2      10.0   318.235692  2110.862094   463.760987  2111.668060  17.400000   
3      11.0   466.041065  3115.240176   580.480240  3115.786719  13.709000   
4       7.0   582.270812  3206.763076   674.847361  3207.141539  11.086000   
5      13.0   677.620031  2562.555780   758.391143  2562.833262   9.651000   
6       6.0   760.194146  2845.702707   814.022705  2845.864668   6.434000   
7      23.0   848.193919  2508.682464   915.068495  2508.839990   7.982000   
8      12.0   917.017730  2590.416285   997.884600  2590.567226   9.650000   
9      17.0   999.976550  2255.510710  1059.953872  2255.592278   7.148000   
10     14.0  1061.463437  1736.042365  1162.622112  1736.120447  12.034000   
11     15.0  1164.968485  2207.112667  1248.038297  2207.129639   9.889000   
12     16.0  1250.044903  2054.830210  1398.331652  2054.744978  17.634001   
13      5.0  1400.132753  2353.718428  1539.419122  2353.510412  16.563000   
14     18.0  1541.458431  2329.673853  1663.831400  2329.385534  14.540000   
15     19.0  1665.788045  2359.358856  1737.049172  2359.145610   8.463000   
16      4.0  1736.810422  3146.599463  1790.970668  3146.418223   6.443000   
17     20.0  1794.506989  2677.048441  1873.828535  2676.744774   9.421000   
18     22.0  1907.359985  2871.480924  2043.039444  2870.839564  16.110001   

    ywidth  curved  position  length     object_1  start_1   end_1  row_1  \
0    0.582     0.0    1782.0   140.0  1865.967810   1859.0  1871.0   21.0   
1    0.582     0.0    1678.0   104.0  1699.510369   1693.0  1705.0   19.0   
2    0.581     0.0    1530.0   148.0  1551.583239   1545.0  1557.0   18.0   
3    0.582     0.0    1415.0   115.0  1524.000000   1518.0  1527.0   17.0   
4    0.582     0.0    1320.0    95.0  1339.825909   1333.0  1345.0   15.0   
5    0.581     0.0    1237.0    83.0  1284.210901   1284.0  1290.0   14.0   
6    0.582     0.0    1181.0    56.0  1205.102243   1199.0  1211.0   12.0   
7    0.581     0.0    1110.0    71.0  1130.720434   1124.0  1136.0   11.0   
8    0.581     0.0    1025.0    85.0          NaN      NaN     NaN    NaN   
9    0.581     0.0     963.0    62.0   984.153813    978.0   990.0   10.0   
10   0.581     0.0     857.0   106.0   877.860752    871.0   883.0    9.0   
11   0.581     0.0     772.0    85.0   792.383223    786.0   798.0    8.0   
12   0.581     0.0     622.0   150.0   679.715176    673.0   685.0    7.0   
13   0.581     0.0     481.0   141.0   501.787655    495.0   507.0    6.0   
14   0.581     0.0     357.0   124.0   377.036047    371.0   383.0    5.0   
15   0.581     0.0     284.0    73.0   304.706783    298.0   310.0    4.0   
16   0.583     0.0     225.0    59.0   244.834064    238.0   250.0    3.0   
17   0.582     0.0     143.0    82.0   195.854140    189.0   201.0    2.0   
18   0.582     0.0       0.0   143.0    58.151527     52.0    64.0    1.0   

       object_2  start_2   end_2  row_2  
0   1793.070994   1787.0  1799.0   20.0  
1           NaN      NaN     NaN    NaN  
2           NaN      NaN     NaN    NaN  
3   1435.749018   1429.0  1441.0   16.0  
4           NaN      NaN     NaN    NaN  
5   1258.301264   1252.0  1264.0   13.0  
6           NaN      NaN     NaN    NaN  
7           NaN      NaN     NaN    NaN  
8           NaN      NaN     NaN    NaN  
9           NaN      NaN     NaN    NaN  
10          NaN      NaN     NaN    NaN  
11          NaN      NaN     NaN    NaN  
12          NaN      NaN     NaN    NaN  
13          NaN      NaN     NaN    NaN  
14          NaN      NaN     NaN    NaN  
15          NaN      NaN     NaN    NaN  
16          NaN      NaN     NaN    NaN  
17          NaN      NaN     NaN    NaN  
18    14.848948      8.0    20.0    0.0

In [34]:
import numpy as np
names = data.field(1)

names = [col.name for col in cols]
print(names)
# Rows in final image for the extracted spectra
print(data['row_1'])  
print(data['row_2'])
print(data['curved'])  # Never curved
print(data['position'])
print(data['xtop'])
# data[:1]
# print(data['object_1'])
# print(data['object_2'])


['slit_id', 'xtop', 'ytop', 'xbottom', 'ybottom', 'xwidth', 'ywidth', 'curved', 'position', 'length', 'object_1', 'start_1', 'end_1', 'row_1', 'object_2', 'start_2', 'end_2', 'row_2']
[21 19 18 17 15 14 12 11 -1 10  9  8  7  6  5  4  3  2  1]
[20 -1 -1 16 -1 13 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1782 1678 1530 1415 1320 1237 1181 1110 1025  963  857  772  622  481
  357  284  225  143    0]
[9.24529549e-01 2.12992077e+02 3.18235692e+02 4.66041065e+02
 5.82270812e+02 6.77620031e+02 7.60194146e+02 8.48193919e+02
 9.17017730e+02 9.99976550e+02 1.06146344e+03 1.16496848e+03
 1.25004490e+03 1.40013275e+03 1.54145843e+03 1.66578805e+03
 1.73681042e+03 1.79450699e+03 1.90735998e+03]
